### ISSUE TITLE
Alternatives to writing .csv files for import into python

### ISSUE THREAD

**Issue by Michael-Elten** [PHACDataHub/hpoc_daily_trend#20]
Right now we write a couple of csv files in R to the shared drive, and then download them back from the shared drive in python. I think there is a way to pass r data frames directly to python so we should explore this as I imagine there will be some time-saving here!

**Comment by hswerdfe** [comment]
you could look into the `reticulate` package `https://rstudio.github.io/reticulate/`

**Comment by Michael-Elten** [comment]
@hswerdfe Thanks, that is basically what I ended up doing! Before we were using "source_python()" from the reticulate package, but I couldn't figure out how to pass R objects in this way.

Last night I copied the .py code into a new .rmd file, and using the python chunk option I was able to successfully pass R objects over to python without needing to write/read csv files.
