### ISSUE TITLE
Generate international table for Infobase on Google Sheets

### ISSUE THREAD

**Issue by najsaqib** [PHACDataHub/hpoc_daily_trend#26]
Infobase lost access to their international data for the world map on their portal, and their server is very tightly secured. As such, they can't just directly pull data from anywhere. However, Google Sheets is whitelisted for them.

As such, we need to output something with the following data schema based on the latest `Our World in Data` data as part of the daily routine: 
https://mapdashbd.s3.ca-central-1.amazonaws.com/download/InternationalCovid19Cases.csv

**Comment by Michael-Elten** [comment]
@najsaqib Currently the trend report is only run Sun-Thus. Is this something that would need to be updated 7 days a week?

**Comment by najsaqib** [comment]
@Michael-Elten I think its fine for this to also remain Sun-Thursday. Infobase can just add a disclaimer to indicate that. Don't want to start a new process just for this.

**Comment by Michael-Elten** [comment]
@najsaqib Okay - because we can also write some code to accomplish this that could piggy-back off an R script run daily by the daily report epi? 

Would we need to create a new Google Sheet for this or is there one already established?

**Comment by najsaqib** [comment]
@Michael-Elten ah didn't realize the daily report epi is also running some R scripts. I will ask Infobase how important is it for it to be ran daily as opposed to Sun-Thurs.

And yes there is no Google Sheets for this currently, so it would need to be established.

**Comment by Michael-Elten** [comment]
@najsaqib Okay thanks - can draft a script to accomplish this in the meantime, and then we can decide later where it is best placed.  This could be a good candidate for a completely autonomous script (run on a set schedule) - if we were to ever go that route

**Comment by najsaqib** [comment]
@Michael-Elten Good point. I can check if we can find some space for this on some of our corporate cloud infrastructure.

**Comment by Michael-Elten** [comment]
See first iteration here: https://docs.google.com/spreadsheets/d/1N0pAuEKgEDBkOMCiuh7jN-7xstMbgPGzCKOlhnWhru4 

In the example excel sheet, there was an `ID` variable that has been replaced with an `iso_code` variable that does not match up - let me know if this is an issue, it can be addressed if needed.

I also have additional variables right now, but the Sheet can be pared down to only exactly what was in the example excel  sheet if needed. Alternatively, other variables can be easily added from what is already present in the OWID source: https://github.com/owid/covid-19-data/tree/master/public/data.

**Comment by najsaqib** [comment]
Oh nice, this is excellent! Should we aim to put it on the cloud right away or can this be run as part of the daily epi trend job for the time being?

**Comment by Michael-Elten** [comment]
How long would it take to be put to the cloud? For now, I would propose that this script is best fit with the daily report epi, as they support infobase data through a Google Sheet already (though I think they don't do this with an R script, but rather manual data entry), and can update this data 7 days a week. I believe the international data gets updated earlier in the day so this task wouldn't clash with others in the evening when they are usually very busy. 

If they share with me the URL to their existing Google sheet, I could also modify my script so that a new worksheet at this same URL is created with this international data, reducing the number of Sheets that need to be maintained. Although we may want to keep them separate to reduce possible crashing issues, as the international data is approaching 100k rows and not sure the stability of writing that much data consistently.

**Comment by najsaqib** [comment]
Ok, lets offload this off to the daily report epi. Do you know who that is? 

I can technically put it on the cloud within a day or two, but I still need to get access to the production DataBricks environment first, plus a bunch of other stuff got put on my plate this morning.

**Comment by najsaqib** [comment]
Thanks for the script @Michael-Elten. I was able to modify it a bit so that it loads the data onto our protected cloud storage account as opposed to Google sheets for Infobase to fetch, and that has been pushed to our existing ETL virtual machine. The job runs once everyday and is fully automated!

**Comment by najsaqib** [comment]
And this is the updated map btw: https://health-infobase.canada.ca/covid-19/international/dev.html

**Comment by Michael-Elten** [comment]
Looks good! going to delete the .R script from this repo then as I presume it will be maintained by your group moving forward.

**Comment by najsaqib** [comment]
Yes, the new code is inside a Github Entreprise repo here, if you access to it: 
https://github.hc-sc.gc.ca/hs/traveller-post/blob/master/src/01_lime_etl.R
