### ISSUE TITLE
Test if you can knit the RMD file successfully now

### ISSUE THREAD

**Issue by najsaqib** [PHACDataHub/hpoc_daily_trend#3]
Please test if you are able to knit the full successfully. You will need to install 'reticulate' package in R, and then do 'py_install("pandas")' at the very least. I want to see if everyone can do those things without needing local admin access.

**Comment by islafar** [comment]
After installing reticulate, pandas, installr, pandoc, and xldr, I managed to knit the RMD file successfully.

**Comment by hswerdfe** [comment]
I get this error, the link works in browser, but does not work in code, unsure why... 

```
df_int <- read.csv("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv", na.strings = "", fileEncoding = "UTF-8-BOM") %>%
+   rename(date = dateRep) %>%
+   mutate(date = as.Date(date, format = "%d/%m/%Y"))
Error in file(file, "rt", encoding = fileEncoding) : 
  cannot open the connection
In addition: Warning message:
In file(file, "rt", encoding = fileEncoding) :
  InternetOpenUrl failed: 'A connection with the server could not be established'
```

But the python code runs fine after I ran


```
#reticulate::py_install("pandas")
#reticulate::py_install("xlrd")

```

**Comment by najsaqib** [comment]
Interesting. Does the ECDC portion still throw an error for you? 

Overall it appears that people are able to run it, although Farzad has admin access as well so its not entirely conclusive lol. And it seems that one will also need to do `py_install("xlrd")` on top of pandas based on you guys' experience, which should not be a problem but will have to be noted in the README/SoP.

**Comment by hswerdfe** [comment]
any idea why I can't read from 
https://opendata.ecdc.europa.eu/covid19/casedistribution/csv 
I know its not what you were trying to test but it seems strange.

**Comment by hswerdfe** [comment]
Yes just tested still throws the error, but still works in browser.

also tried this 
`download.file("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv", "ecdc.csv")`
and it failed also

**Comment by najsaqib** [comment]
Huh. Does `read_csv("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv")` work for you by any chance?

**Comment by hswerdfe** [comment]
alas still a no go...

`> read_csv("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv")
Error in open.connection(con, "rb") : 
  schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed).`

**Comment by najsaqib** [comment]
That is very odd. Are you able to directly read any csv file from anywhere?

**Comment by najsaqib** [comment]
nevermind the above question, if the portion of the coding importing the data infobase is not throwing an error means you can read csv file from online

**Comment by h-aujla** [comment]
I was able to knit the report successfully after installing minconda, and then running py_install("pandas") and py_install("xlrd")

**Comment by najsaqib** [comment]
Oh nice. I will close this issue then, and note in the README that both `pandas` and `xlrd` are necessary to install. Will need to look into Howard's issue separately 👀
