### ISSUE TITLE
Incorporate ability to include footnotes

### ISSUE THREAD

**Issue by islafar** [PHACDataHub/hpoc_daily_trend#4]
Sometimes data have caveats. For example, the national total for hospitalizations often exclude Alberta as they have delays in their reporting. The markdown file or the underlying R script need the ability to customize for this. Perhaps a parameter?

**Comment by Michael-Elten** [comment]
This is currently being accomplished through several different ways: fig.cap chunk option, flextable::footnote(), ggplot captions, and python captions. 

Will need to look into further options for "fig.cap()" such as how to modify text size and alignment

**Comment by Michael-Elten** [comment]
I think we can close this issue as it is largely addressed. New issues can be made to address formatting of different footnotes as needed
