### ISSUE TITLE
Ability to select which slides to update

### ISSUE THREAD

**Issue by islafar** [PHACDataHub/hpoc_daily_trend#5]
Currently, only hospitalization/ICU and cases/deaths by PT are updated daily. All other data is updated on Mondays and Thursdays, with the exception of weekly lab-testing data which is updated only on Mondays. The markdown file should provide the ability to select which slides to update.

**Comment by Michael-Elten** [comment]
Currently, the trend report updates all slides every day (though lab testing table only changes dates on Mondays, numbers are recalculated for the previous week daily).

I think this is a better solution. If we want to add ability to generate only certain slides for the purposes of quicker debugging, we can look into adding and modifying eval="" statements for the different code chunks that will allow us to selectively run different parts of the report.
