### ISSUE TITLE
Make date a parameter for the report

### ISSUE THREAD

**Issue by najsaqib** [PHACDataHub/hpoc_daily_trend#9]
Use R-Markdown's parameter function

**Comment by Michael-Elten** [comment]
Will need to apply param$date filters immediately after importing data via functions now. Will explore once integration with package is complete

**Comment by Michael-Elten** [comment]
Closing this issue for now as we don't have a need to run trend reports for previous days (as CRF and SALT get updated retrospectively anyways, this may not be useful anyways). 

We keep previous trend reports saved in a repository now anyways so perhaps this feature won't ever be needed.
